{% set name = "openinference-instrumentation-anthropic" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_anthropic-{{ version }}.tar.gz
  sha256: fc78ac8d7078dc24ee72851c598b22780e4c7a6d66f627c2dd94c5402e4a6ce3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.15
    - openinference-semantic-conventions
    - wrapt
    - typing-extensions

test:
  imports:
    - openinference.instrumentation.anthropic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Arize-ai/openinference
  summary: OpenInference Anthropic Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
